
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FSE.ProjectManagementPortal.DataAccess.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {

        this.Tasks = new HashSet<Task>();

    }


    public int User_ID { get; set; }

    public string Employee_ID { get; set; }

    public string First_Name { get; set; }

    public string Last_Name { get; set; }

    public Nullable<int> Project_ID { get; set; }

    public Nullable<int> Task_ID { get; set; }

    public Nullable<bool> IsActive { get; set; }



    public virtual Project Project { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Task> Tasks { get; set; }

    public virtual Task Task { get; set; }

}

}
